local lunarised = require('lunarised.colours')

local theme = {
	base = {
		Boolean = { fg = lunarised.green },
		Character = { fg = lunarised.orange },
		ColorColumn = { fg = lunarised.none, bg = lunarised.bg_alt },
		Conceal = { fg = lunarised.disabled },
		Conditional = { fg = lunarised.green },
		Constant = { fg = lunarised.purple },
		CursorColumn = { fg = lunarised.none, bg = lunarised.bg_alt },
		CursorLine = { fg = lunarised.none, bg = lunarised.bg_alt },
		CursorLineNr = { fg = lunarised.accent, bg = lunarised.smoke },
		Debug = { fg = lunarised.red },
		Define = { fg = lunarised.blue },
		Delimiter = { fg = lunarised.red },
		DiffAdd = { fg = lunarised.green, bg = lunarised.none, style = 'reverse' },
		DiffChange = { fg = lunarised.orange, bg = lunarised.none, style = 'reverse' },
		DiffDelete = { fg = lunarised.red, bg = lunarised.none, style = 'reverse' },
		DiffText = { fg = lunarised.purple, bg = lunarised.none, style = 'reverse' },
		Directory = { fg = lunarised.blue, bg = lunarised.none },
		EndOfBuffer = { fg = lunarised.bg },
		Error = { fg = lunarised.error, bg = lunarised.none },
		ErrorMsg = { fg = lunarised.none },
		Exception = { fg = lunarised.red },
		Float = { fg = lunarised.orange },
		FoldColumn = { fg = lunarised.blue },
		Folded = { fg = lunarised.disabled, bg = lunarised.none, style = 'italic' },
		Function = { fg = lunarised.blue },
		Identifier = { fg = lunarised.purple },
		Ignore = { fg = lunarised.disabled },
		IncSearch = { fg = lunarised.highlight, bg = lunarised.white, style = 'reverse' },
		Include = { fg = lunarised.red },
		Keyword = { fg = lunarised.yellow },
		Label = { fg = lunarised.purple },
		LineNr = { fg = lunarised.line_numbers },
		Macro = { fg = lunarised.green },
		MatchParen = { fg = lunarised.white, bg = lunarised.highlight },
		ModeMsg = { fg = lunarised.accent },
		MoreMsg = { fg = lunarised.accent },
		NonText = { fg = lunarised.disabled },
		Normal = { fg = lunarised.fg, bg = lunarised.bg },
		NormalFloat = { fg = lunarised.fg, bg = lunarised.float },
		Number = { fg = lunarised.orange },
		Operator = { fg = lunarised.purple },
		Pmenu = { fg = lunarised.bg, bg = lunarised.contrast },
		PmenuSbar = { fg = lunarised.fg, bg = lunarised.contrast },
		PmenuSel = { fg = lunarised.bg, bg = lunarised.active },
		PmenuThumb = { fg = lunarised.fg, bg = lunarised.accent },
		PreCondit = { fg = lunarised.cyan },
		PreProc = { fg = lunarised.yellow },
		Question = { fg = lunarised.green },
		QuickFixLine = { fg = lunarised.highlight, bg = lunarised.white, style = 'reverse' },
		Repeat = { fg = lunarised.green },
		Search = { fg = lunarised.highlight, bg = lunarised.white, style = 'reverse' },
		Special = { fg = lunarised.fg },
		SpecialChar = { fg = lunarised.purple },
		SpecialComment = { fg = lunarised.grey },
		SpecialKey = { fg = lunarised.error },
		SpellBad = { fg = lunarised.red, bg = lunarised.none, style = 'undercurl' },
		SpellCap = { fg = lunarised.blue, bg = lunarised.none, style = 'undercurl' },
		SpellLocal = { fg = lunarised.cyan, bg = lunarised.none, style = 'undercurl' },
		SpellRare = { fg = lunarised.yellow, bg = lunarised.none, style = 'undercurl' },
		Statement = { fg = lunarised.blue },
		StatusLine = { fg = lunarised.fg, bg = lunarised.bg_alt },
		StatusLineNC = { fg = lunarised.fg, bg = lunarised.bg_alt },
		StatusLineTerm = { fg = lunarised.fg, bg = lunarised.contrast },
		StatusLineTermNC = { fg = lunarised.fg, bg = lunarised.disabled },
		StorageClass = { fg = lunarised.cyan },
		String = { fg = lunarised.cyan, bg = lunarised.none },
		Structure = { fg = lunarised.puple },
		TabLineFill = { fg = lunarised.fg },
		Tabline = { fg = lunarised.fg },
		TablineSel = { fg = lunarised.bg, bg = lunarised.accent },
		Tag = { fg = lunarised.red },
		Title = { fg = lunarised.grey, bg = lunarised.none, style = 'bold' },
		Todo = { fg = lunarised.purple, bg = lunarised.none, style = 'bold' },
		ToolbarButton = { fg = lunarised.fg, bg = lunarised.none, style = 'bold' },
		ToolbarLine = { fg = lunarised.fg, bg = lunarised.bg_alt },
		Type = { fg = lunarised.yellow },
		Typedef = { fg = lunarised.red },
		Underlined = { fg = lunarised.link, bg = lunarised.none, style = 'underline' },
		VertSplit = { fg = lunarised.active, bg = lunarised.none },
		Visual = { fg = lunarised.none, bg = lunarised.selection },
		VisualNOS = { fg = lunarised.none, bg = lunarised.selection },
		WarningMsg = { fg = lunarised.orange },
		Warnings = { fg = lunarised.orange },
		WildMenu = { fg = lunarised.orange, bg = lunarised.none, style = 'bold' },
		diffAdded = { fg = lunarised.green },
		diffChanged = { fg = lunarised.purple },
		diffFile = { fg = lunarised.blue },
		diffIndexLine = { fg = lunarised.yellow },
		diffLine = { fg = lunarised.comments },
		diffNewFile = { fg = lunarised.orange },
		diffOldFile = { fg = lunarised.yellow },
		diffRemoved = { fg = lunarised.red },
		mkdURL = { fg = lunarised.purple },
		qfLineNr = { fg = lunarised.highlight, bg = lunarised.white, style = 'reverse' },
	},

	treesitter = {
		TSAnnotation = { fg = lunarised.red, style = 'bold' },
		TSAttribute = { fg = lunarised.blue },
		TSBoolean= { fg = lunarised.green },
		TSCharacter= { fg = lunarised.orange },
		TSConditional = { fg = lunarised.green },
		TSConstBuiltin = { fg = lunarised.blue },
		TSConstMacro = { fg = lunarised.blue },
		TSConstant = { fg = lunarised.yellow },
		TSConstructor = { fg = lunarised.yellow },
		TSEmphasis = { fg = lunarised.grey, style = 'bold' },
		TSError = { fg = lunarised.error },
		TSException = { fg = lunarised.red, style = 'bold' },
		TSField = { fg = lunarised.purple },
		TSFloat = { fg = lunarised.red },
		TSFuncBuiltin = { fg = lunarised.fg },
		TSFuncMacro = { fg = lunarised.blue },
		TSFunction = { fg = lunarised.blue },
		TSInclude = { fg = lunarised.orange, style = 'bold' },
		TSKeyword = { fg = lunarised.orange },
		TSKeywordFunction = { fg = lunarised.orange, style = 'bold' },
		TSLabel = { fg = lunarised.purple },
		TSLiteral = { fg = lunarised.fg },
		TSMethod = { fg = lunarised.fg },
		TSNamespace = { fg = lunarised.purple },
		TSNone = { },
		TSNumber = { fg = lunarised.orange },
		TSOperator = { fg = lunarised.purple },
		TSParameterReference= { fg = lunarised.green },
		TSProperty = { fg = lunarised.green },
		TSPunctBracket = { fg = lunarised.fg },
		TSPunctDelimiter = { fg = lunarised.fg },
		TSPunctSpecial = { fg = lunarised.purple },
		TSRepeat = { fg = lunarised.green, style = 'bold' },
		TSStrike = { },
		TSString = { fg = lunarised.cyan },
		TSStringEscape = { fg = lunarised.disabled },
		TSStringRegex = { fg = lunarised.blue },
		TSSymbol = { fg = lunarised.cyan },
		TSTag = { fg = lunarised.blue },
		TSTagDelimiter = { fg = lunarised.blue },
		TSText = { fg = lunarised.fg },
		TSTextReference = { fg = lunarised.purple },
		TSTitle = { fg = lunarised.grey, bg = lunarised.none, style = 'bold' },
		TSType = { fg = lunarised.yellow },
		TSTypeBuiltin = { fg = lunarised.yellow },
		TSURI = { fg = lunarised.link },
		TSUnderline = { fg = lunarised.fg, bg = lunarised.none, style = 'underline' },
		TSVariable = { fg = lunarised.fg },
		TSVariableBuiltin = { fg = lunarised.blue },
		TSWarning = { fg = lunarised.white, bg = lunarised.orange },
	},

	plugins = {
		-- GitGutter
		GitGutterAdd = { fg = lunarised.green },
		GitGutterChange = { fg = lunarised.purple },
		GitGutterDelete = { fg = lunarised.red },
		SignColumn = { bg = lunarised.none },

		-- NERDTree
		NERDTreeCWD = { fg = lunarised.fg },
		NERDTreeDir = { fg = lunarised.contrast },
		NERDTreeDirSlash = { fg = lunarised.fg },
		NERDTreeExecFile = { fg = lunarised.highlight },
		NERDTreeHelp = { fg = lunarised.fg },
		NERDTreeUp = { fg = lunarised.disabled },
	}
}

if vim.g.lunarised_italic_comments == true then
	theme.treesitter.TSComment= { fg = lunarised.comments, bg = lunarised.none, style = 'italic' }
	theme.base.Comment = { fg = lunarised.comments, bg = lunarised.none, style = 'italic' }
else
	theme.treesitter.TSComment = { fg = lunarised.comments }
	theme.base.Comment = { fg = lunarised.comments }
end

return theme
